# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            '<h3>Voice conversion demo</h3>'
tagline:          'A Jekyll theme'
description:      'This is a demo page for <a href="http://jekyllrb.com" target="_blank">Voice Conversion</a>.'
url:              'https://lhppom.github.io/VoiceConversion/'
baseurl:          /

author:
  name:           'lhppom'
  url:            'https://lhppom.github.io/VoiceConversion/'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           'https://github.com/lhppom/VoiceConversion/'
